### ISSUE TITLE
Upcoming hard fork [view tags?]

### ISSUE THREAD

**Issue by plowsof** [monero-ecosystem/monero-python#113]
Hello, the upcoming Monero hard fork will be introducing [view-tags](https://github.com/monero-project/monero/pull/8061)

It would be nice to have this supported by the [outputs function](https://github.com/monero-ecosystem/monero-python/blob/d48d615162b0b950549990bf182bcf4fc630c731/monero/transaction/__init__.py#L136)

**Comment by emesik** [comment]
I agree it would be great. Anyone willing to submit a PR?

**Comment by plowsof** [comment]
I reached out to @j-berman who confirms that the json will appear as :
```
{ 
  "target": {
    "tagged_key": {
      "key": "ea3f...",
      "view_tag": "a1"
    }
  }
}
```
and offered his initial suggestion of how it may end up looking like - and because older transactions will not have view_tags, we must ```try:``` if one is set first.

specifically [this function](https://github.com/monero-ecosystem/monero-python/blob/d48d615162b0b950549990bf182bcf4fc630c731/monero/transaction/__init__.py#L143)
```
svk_8 = ed25519.scalar_add(svk_4, svk_4)

shared_secret = ed25519.scalarmult(svk_8, tx_key)
vt_hsdata = b"".join([
                       onchain_view_tag, # need to make sure to only take first 8 bytes of this string
                       shared_secret,
                       varint.encode(idx)
])
vt_full = keccak_256(vt_hsdata).digest()
vt = vt_full[0] # the view tag is the first byte of vt_full

if vt != onchain_view_tag:
    continue
hsdata = b"".join([
                     shared_secret,
                     varint.encode(idx),
])
Hs_ur = keccak_256(hsdata).digest()    
```
However as you can see, the on chain view tag is required here ^ hopefully you can shed some light on how to get the viewkey to this from the place you are accessing / parsing the vout json (again , this part will break as the structure will be that of what is above)
https://github.com/monero-ecosystem/monero-python/blob/d48d615162b0b950549990bf182bcf4fc630c731/monero/transaction/__init__.py#L203

**Comment by emesik** [comment]
What is the height/date of scheduled release to the testnet?

**Comment by emesik** [comment]
So far, I rebased it and merged into the [viewtags branch](https://github.com/monero-ecosystem/monero-python/compare/master...viewtags).

**Comment by plowsof** [comment]
Thanks!

I have read that it is usually 1 month prior to the hard fork date , so we would expect it to be 16th June, but i will confirm those details for you.

**Comment by plowsof** [comment]
Testnet hard-fork: May 16th, 2022, block 1982800 and 1983520
  Stagenet hard-fork: July 9th
  Mainnet hard-fork: July 16th, 2022, block 2668888

**Comment by emesik** [comment]
Thank you! I'm adding these dates into my calendar.

**Comment by emesik** [comment]
Merged and released
