### ISSUE TITLE
module 'nacl.bindings' has no attribute 'crypto_core_ed25519_add'

### ISSUE THREAD

**Issue by Hernes998** [monero-ecosystem/monero-python#121]
I'm getting this error

  File "/home/username/.local/lib/python3.8/site-packages/monero/ed25519.py", line 4, in <module>
    edwards_add = nacl.bindings.crypto_core_ed25519_add
AttributeError: module 'nacl.bindings' has no attribute 'crypto_core_ed25519_add'

**Comment by emesik** [comment]
Could you please paste the output of what the command `pip freeze` outputs?
Or, at least, `pip freeze | grep -i nacl`?
