### ISSUE TITLE
Get full balance from an address and send funds from that address

### ISSUE THREAD

**Issue by r3nor** [monero-ecosystem/monero-python#122]
I have an address with a payment ID and I want to see the current balance of that address. Do I need to add all incoming transactions, or is there a way to directly get the balance?

Another question is that I would like to send the funds from an address. Say, I want to empty an address that received a transaction. How can this be done? Right now, I am only able to send transactions from my wallet, but I am not able to select which funds I want to spend. 

Also, can I use a payment_id to "label" an outgoing transaction?

Thank you for maintaining this library.

**Comment by euri10** [comment]
can use also integrated address with a payment id
https://monero-python.readthedocs.io/en/latest/address.html#payment-ids-and-integrated-addresses

**Comment by r3nor** [comment]
Thank you for your answers! These were very helpful. I made use of subaddresses :)

**Comment by emesik** [comment]
Regarding the per-address balance, I've implemented it in a385a6146e813b94c458dfb4a88c610e3dc5f083
