### ISSUE TITLE
Sweep function

### ISSUE THREAD

**Issue by nyxynyx** [monero-ecosystem/monero-python#20]
Is there a method for using the `monero-wallet-cli` `sweep_all` command to transfer all the funds from the current wallet to another wallet?

**Comment by emesik** [comment]
Currently it's not available, because I assumed that command is rarely used in automated environment. However, the implementation should be straightforward, so I'll try to include it in the next release.

**Comment by Lafudoci** [comment]
I need this function too. Since now monero have accounts system, my service needs transfer fund between accounts. I could not figure out a reliable way to withdraw all balance without use `weep_all`. I guess I have to calculating the tx size * fee/kb. But did not figure out.

**Comment by emesik** [comment]
An alternative is to call `transfer()` with `relay=False`. The resulting transaction won't be submitted to the network but you may learn the fee amount from it and recalculate amounts again. Of course, this is a nasty workaround and prone to bugs (recalculating amount may include different set of UTXOs, changing the size and resulting fee of the transaction).

I'll add it ASAP.

**Comment by dginovker** [comment]
I would also prefer `sweep_all` over this method. Are there still plans to implement it?

**Comment by emesik** [comment]
It has been added. Feel free to test it. I'll also run some additional checks and release it this week.
