### ISSUE TITLE
Wallet().transfer() method leaking memory on giving amount as string.

### ISSUE THREAD

**Issue by nandubatchu** [monero-ecosystem/monero-python#48]

**Comment by emesik** [comment]
Can you elaborate?

**Comment by nandubatchu** [comment]
@emesik when I tried specifying the 'amount' parameter in the transfer() method in string, There is some kind of recursive loop happening and the memory footprint of the application keeps rising exponentially.

**Comment by emesik** [comment]
There's no type check and string ends up being multiplicated 10^12 times and concatenated to self. No wonder it causes memory errors. Quite funny bug :)

I've got a fix for that already, expect `ValueError` to be thrown. Just running tests to reassure everything works, and I'm releasing 0.5.2 today.

Thanks!
