### ISSUE TITLE
Add validate_address function to JSONRPCDaemon

### ISSUE THREAD

**Issue by ghost** [monero-ecosystem/monero-python#51]
Recent addition to the wallet rpc is the validate_address method.
https://github.com/monero-project/monero/pull/5141/commits/5c81a9f1a113e6932b019ba9f0d72b9ccd7cf743

This would be a great addition to the JSONRPCDaemon

**Comment by emesik** [comment]
`monero.address.address()` already does all the validation offline.

IIUC, the only missing part there is openalias lookup, which could be also implemented without RPC. Or I'm missing something?

**Comment by lalanza808** [comment]
User account was deleted, I think we can close this. Doesn't seem to add much value anyways unless many people need that openalias validation.

**Comment by emesik** [comment]
You're right. Openalias could be a good addition, though.
