### ISSUE TITLE
Installing monero-python with python3 in windows 10

### ISSUE THREAD

**Issue by darlzkrish27** [monero-ecosystem/monero-python#58]
installing sha3 is getting problematic in python3 in windows, I don't know whats happening

    Collecting sha3
    Downloading 
    Building wheels for collected packages: sha3
    Building wheel for sha3 (setup.py) ... error
    ERROR: Command errored out with exit status 1:
    command: 'c:\users\prathap g v\appdata\local\programs\python\python37-32\python.exe' -u -c 
    'import sys, setuptools, tokenize; sys.argv[0] = 
    '"'"'C:\\Users\\PRATHA~1\\AppData\\Local\\Temp\\pip-install-p8ic2zmq\\sha3\\setup.py'"'"'; 
    __file__='"'"'C:\\Users\\PRATHA~1\\AppData\\Local\\Temp\\pip-install- 
     p8ic2zmq\\sha3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open) 
    (__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, 
     '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\PRATHA~1\AppData\Local\Temp\pip-wheel-gb1o6ohw' -- 
     python-tag cp37
       cwd: C:\Users\PRATHA~1\AppData\Local\Temp\pip-install-p8ic2zmq\sha3\
       Complete output (10 lines):
      running bdist_wheel
      running build
       running build_py
      creating build
      creating build\lib.win32-3.7
      creating build\lib.win32-3.7\sha3
      copying sha3\__init__.py -> build\lib.win32-3.7\sha3
      running build_ext
      building '_sha3' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": 
      https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for sha3
  Running setup.py clean for sha3
Failed to build sha3
Installing collected packages: sha3
    Running setup.py install for sha3 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\prathap g v\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PRATHA~1\\AppData\\Local\\Temp\\pip-install-p8ic2zmq\\sha3\\setup.py'"'"'; __file__='"'"'C:\\Users\\PRATHA~1\\AppData\\Local\\Temp\\pip-install-p8ic2zmq\\sha3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PRATHA~1\AppData\Local\Temp\pip-record-08ajzxis\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\PRATHA~1\AppData\Local\Temp\pip-install-p8ic2zmq\sha3\
    Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\sha3
    copying sha3\__init__.py -> build\lib.win32-3.7\sha3
    running build_ext
    building '_sha3' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\prathap g v\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PRATHA~1\\AppData\\Local\\Temp\\pip-install-p8ic2zmq\\sha3\\setup.py'"'"'; __file__='"'"'C:\\Users\\PRATHA~1\\AppData\\Local\\Temp\\pip-install-p8ic2zmq\\sha3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PRATHA~1\AppData\Local\Temp\pip-record-08ajzxis\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

that is the log i'm getting

**Comment by emesik** [comment]
I guess you have installed _Microsoft Visual C++ Build Tools_?

Unfortunately I can't help you personally, as I have zero experience with development on Windows and no test platform around.

**Comment by tiedtoastar** [comment]
https://www.scivision.dev/python-windows-visual-c-14-required/
This problem is not unique to monero-python. Recommend closing

**Comment by emesik** [comment]
Ok, thanks!
