### ISSUE TITLE
Add support for filtering transfers by tx_id

### ISSUE THREAD

**Issue by tiedtoastar** [monero-ecosystem/monero-python#59]
monero rpc has this function: 

`get_transfer_by_txid

Show information about a transfer to/from this address.

Alias: None.

Inputs:

    txid - string; Transaction ID used to find the transfer.
    account_index - unsigned int; (Optional) Index of the account to query for the transfer.

Outputs:

    transfer - JSON object containing payment information:
        address - string; Address that transferred the funds. Base58 representation of the public keys.
        amount - unsigned int; Amount of this transfer.
        confirmations - unsigned int; Number of block mined since the block containing this transaction (or block height at which the transaction should be added to a block if not yet confirmed).
        destinations - array of JSON objects containing transfer destinations:
            amount - unsigned int; Amount transferred to this destination.
            address - string; Address for this destination. Base58 representation of the public keys.
        double_spend_seen - boolean; True if the key image(s) for the transfer have been seen before.
        fee - unsigned int; Transaction fee for this transfer.
        height - unsigned int; Height of the first block that confirmed this transfer.
        note - string; Note about this transfer.
        payment_id - string; Payment ID for this transfer.
        subaddr_index - JSON object containing the major & minor subaddress index:
            major - unsigned int; Account index for the subaddress.
            minor - unsigned int; Index of the subaddress under the account.
        suggested_confirmations_threshold - unsigned int; Estimation of the confirmations needed for the transaction to be included in a block.
        timestamp - unsigned int; POSIX timestamp for the block that confirmed this transfer (or timestamp submission if not mined yet).
        txid - string; Transaction ID of this transfer (same as input TXID).
        type - string; Type of transfer, one of the following: "in", "out", "pending", "failed", "pool"
        unlock_time - unsigned int; Number of blocks until transfer is safely spendable.
`

I would like to be able to retrieve a transaction that matches the txid that is passed via parameter.

Example: my_tx = mywallets["XMR"].incoming(txid=payment_record.txid)

**Comment by emesik** [comment]
Like this? https://github.com/monero-ecosystem/monero-python/blob/019d0b6427307d75556fee08ca4a991c731fcc70/tests/test_jsonrpcwallet.py#L493

**Comment by tiedtoastar** [comment]
My apologies, the requirements file I have in my project just states monero-python. 
The version that was pulled down is old 0.5.4.
I believe pypi needs to be updated to the new versions: https://pypi.org/project/monero-python/

**Comment by emesik** [comment]
Alright. Sorry for the inconvenience. I wanted to notify the developers who use old name in requirements, but as soon as I changed the name, Github hid the list of depending projects and I couldn't retrieve it anymore.

There's a new page at pypi: https://pypi.org/project/monero/
