### ISSUE TITLE
daemon.send_transaction Fails due to recieving tx.blob as bytes

### ISSUE THREAD

**Issue by amnzaza** [monero-ecosystem/monero-python#63]
monero python version => 0.7.1

I traced the error and found out that since tx.blob is received as bytes array in raw_requests(), json.dumps fails due to needing to receive a string instead of a bytes array

I converted the byte array to a string using decode("utf-8") and it seems to be working.

In the wallet-rpc after sending transaction I get this:
`2020-04-12 13:27:28.616 E Cannot calculate the hash of a pruned transaction
2020-04-12 13:27:28.617 E Cannot calculate the hash of a pruned transaction
2020-04-12 13:27:28.618 E Failed to calculate transaction hash`
What does this mean exactly? I get this without any node mining the blocks only.

And in monerod,
`2020-04-12 13:27:12.075 I transaction with hash d39c7ed095e0a4a090678cb3a8bdfcaa49ecd620858a2883583822ce3a2665e9 not found in db
2020-04-12 13:27:12.076 I transaction with hash d39c7ed095e0a4a090678cb3a8bdfcaa49ecd620858a2883583822ce3a2665e9 not found in db
2020-04-12 13:27:12.078 I Transaction added to pool: txid <d39c7ed095e0a4a090678cb3a8bdfcaa49ecd620858a2883583822ce3a2665e9> weight: 300 fee/byte: 1.33333e+07`
Is the transaction being sent twice? 

Please update accordingly. Thank you.

**Comment by emesik** [comment]
Commit 3ad3a6082ba237485ba410cb62b9642aea93a84c should fix the encoding issue. Could you please check it?

As for the RPC error message, it seems to be a different issue but I'm not sure. If that repeats after the fix, please provide more details of the transaction you're trying to send.

**Comment by amnzaza** [comment]
It is working now thanks. As for the RPC problem, it is unrelated to the moneropython.

You can close the issue.

**Comment by emesik** [comment]
FYI version 0.7.2 including this bugfix has been just released.

Thanks for your help!
