### ISSUE TITLE
PyPi.org/simple gives 2+ year outdated version

### ISSUE THREAD

**Issue by dginovker** [monero-ecosystem/monero-python#64]
https://pypi.org/simple/ is the default repository for a lot of Python package searchers (including PyCharm), but monero-python is only on version 0.5.4 there: https://pypi.org/simple/monero-python/

Interestingly, https://pypi.org/project/monero/ shows monero-python on version 0.7.2. I'm not sure where to create the issue, so I'm creating it here to let the maintainers know.

**Comment by dginovker** [comment]
I'm a fool. It's called monero not monero-python now.

**Comment by emesik** [comment]
Sorry you had to waste time figuring it out. I'd like to make PyPi somehow redirect to the new address but there's no obvious way of doing it.

**Comment by foso73** [comment]
Can you just delete the old one from pypi?
@emesik 
https://pypi.org/project/monero-python/

**Comment by emesik** [comment]
Seems like a good idea. Deleted.
