### ISSUE TITLE
Removed PyPi package 'monero-python'.

### ISSUE THREAD

**Issue by normoes** [monero-ecosystem/monero-python#68]
We only recently found that the PyPI papckage `monero-python` is not present anymore - our pipelines failed.

As it turned out, it was renamed to `monero`. This might have been mentioned somewhere, but this bit of information did not reach us in time.

**Even more important** is the fact that the PyPI project `monero-python` was deleted and therefore was made available to the public again.
Since this could have been misused maliciously, we decided to take that project name and "occupy" it on PyPI.

Have a look here: https://pypi.org/project/monero-python/

The goal is to prevent anybody from taking over and introducing malicious code into projects using the _old_ package.

If you would like to take over again, that's no problem, just contact the temporary owner: https://github.com/dethos

Best regards.

**Comment by emesik** [comment]
Thank you very much for protecting that package. It was a stupid oversight from my side to just leave it open to public.

As for the renaming itself, it seems PyPi doesn't offer any way to notify users of the name change or even add any kind of _obsoletes_/_replaces_ keyword. At least I couldn't find it.
