### ISSUE TITLE
ValueError: Excessive arguments for <class 'monero.transaction.IncomingPayment'>: {'destinations': [(xxx, Decimal('zzzz'))]}

### ISSUE THREAD

**Issue by dwjorgeb** [monero-ecosystem/monero-python#71]
I keep getting these sporadic errors when filtering incoming transactions by TXID:

```
ValueError: Excessive arguments for <class 'monero.transaction.IncomingPayment'>: {'destinations': [(xxxx, Decimal('zzzz'))]}
  File "xmr/utils.py", line 61, in get_tx_by_txid
    return wallet.incoming(tx_id=txid, unconfirmed=True)
  File "monero/transaction.py", line 114, in __call__
    return fetch(self.account_idx, PaymentFilter(**filterparams))
  File "monero/backends/jsonrpc.py", line 320, in transfers_in
    return list(pmtfilter.filter(map(self._inpayment, pmts)))
  File "monero/transaction.py", line 243, in filter
    key=_ByHeight)
  File "monero/backends/jsonrpc.py", line 368, in _inpayment
    return IncomingPayment(**self._paymentdict(data))
  File "monero/transaction.py", line 32, in __init__
    raise ValueError("Excessive arguments for {}: {}".format(type(self), kwargs))
```

Any idea why?

**Comment by emesik** [comment]
Interesting. Could you provide more details?

 * Which version of monero are you using?
 * Could you run the code with `DEBUG` log level and pass the RPC request+response corresponding to this query?
 * Is it possible the payment that causes the error is from your wallet back to itself?

I'm wondering how did a payment with `destinations` come up within `incoming`. This shouldn't happen.

**Comment by dwjorgeb** [comment]
> 
> 
> Interesting. Could you provide more details?
> 
>     * Which version of monero are you using?
> 
>     * Could you run the code with `DEBUG` log level and pass the RPC request+response corresponding to this query?
> 
>     * Is it possible the payment that causes the error is from your wallet back to itself?
> 
> 
> I'm wondering how did a payment with `destinations` come up within `incoming`. This shouldn't happen.

After further inspection, it is indeed that a payment is made from the wallet back to itself. Thank you!

**Comment by emesik** [comment]
Good! I haven't tested such scenario yet. Syncing the stagenet test environment now and hope to have the fix ready soon.

**Comment by emesik** [comment]
Just FYI, the transfer back to same wallet will not show among `incoming()` when you query by other criteria than `tx_id=`. This is because the backend uses another RPC method then, and Monero intentionally shows such payments only as outgoing.

This ticket explains more: https://github.com/monero-project/monero/issues/6909
