### ISSUE TITLE
MyMonero Error fetching

### ISSUE THREAD

**Issue by parmen1** [monero-ecosystem/monero-python#74]
Hi community,

following issue. Before few days i used Mymonero without issues.
Now since few Days, i cant receive my monero on 1.1.18 (newest Version) an older version diesnt work too. I get the error "error fetching mymonero updates" day before all works, now this big error https://prnt.sc/vwgtzm , i cant open the wallet on webwallet because lost my seed, how i can repair it? Have access to the wallet, but before i get this error message and the wallet dont synchronisate.

Is it possible to look my seed in MyMonero Account, with my Password? Thank you for help!

kidn regards

**Comment by emesik** [comment]
This error has nothing to do with our project. Please report to mymonero admins or ask at Monero subreddit.
