### ISSUE TITLE
Feature: Add New Class To Represent Stealth Addresses

### ISSUE THREAD

**Issue by jeffro256** [monero-ecosystem/monero-python#77]
Howdy, I am a big fan of this library and I use it a lot for personal analytics. I like the good work put into this project. I think it would be beneficial to add a class to represent stealth addresses (one-time public keys) for completeness sake and because the monero daemon handles them so clumsily. If I want to look up information on a stealth address, I can the the command /get_outs but that requires me to know a "global index" as well as the amount transferred to that output. Alternatively, I could pass a transaction hash to /get_transactions and parse through the JSON to learn information about the stealth address. However, as of right now, the Transaction class in the project does not contain information on the output indices which are given by the /get_transactions command because there are returned in the JSON response outside of the "as_json" key.

Anyways, code would probably be more helpful than an explanation. I can write this code in no time, but I wanted to guage y'alls opinions on this idea. Cheers!

**Comment by emesik** [comment]
Every PR will be welcome. Stealth addresses are certainly useful piece of data, so let's have them. However, please remember to provide some tests as well.

**Comment by emesik** [comment]
This is done :)
