### ISSUE TITLE
[FR] ring_size/mixin for account/transfer func

### ISSUE THREAD

**Issue by mrx23dot** [monero-ecosystem/monero-python#92]
Please add the missing parameters in the RPC call for increased privacy.

ring_size - unsigned int; Number of outputs to mix in the transaction (this output + N decoys from the blockchain).
mixin - unsigned int; Number of outputs from the blockchain to mix with (0 means no mixing).

details: https://www.getmonero.org/resources/developer-guides/wallet-rpc.html

**Comment by mrx23dot** [comment]
Also when using wallet.sweep_all() RPC complains about:
2021-03-06 22:47:34.626 W Requested ring size 1 too low, using 11

**Comment by t-900-a** [comment]
> ring_size - unsigned int; Number of outputs to mix in the transaction (this output + N decoys from the blockchain).
That param should be deprecated upstream or perhaps clarified within the docs.

Monero default ring size is 11 and it can't be modified. This was a change a while ago.

https://github.com/monero-project/monero/issues/4229
