### ISSUE TITLE
Build an RPC interface node that can be used for development

### ISSUE THREAD

**Issue by chenluyong** [monero-ecosystem/monero-python#96]
Where is the tutorial on the RPC interface and full-node running guide?
There is no example file to start RPC, look like [bitcoin.conf](https://github.com/bitcoin/bitcoin/blob/e797388f8b91235c06a9589e3258c476c837f897/share/examples/bitcoin.conf).

I want to run `monerod` to synchronize the full-node of `mainnet` and open the RPC to the outside, and control the local wallet by running `monero-wallet-rpc` and opening the RPC to the outside.

Are there any guidelines for what I should do?

**Comment by lalanza808** [comment]
This is a pretty good resource: https://monerodocs.org/interacting/monerod-reference/

I wouldn't recommend exposing a wallet's RPC interface to the public; run it locally and write scripts/applications to interface with the local interface.

**Comment by chenluyong** [comment]
Thank you for your suggestion, It's very helpful.
full-node has been synchronized.
