### ISSUE TITLE
from the monero-etl : after run "pip install git+https://github.com/emesik/monero-python.git" ,I can not find monero-python.py

### ISSUE THREAD

**Issue by yourprogrameiswrong** [monero-ecosystem/monero-python#99]
from the monero-etl : after run "pip install git+https://github.com/emesik/monero-python.git" ,I can not find monero-python. so next step running "python monero-python" , the server return "python: can't open file 'monero-etl': [Errno 2] No such file or directory". ps, the step of "pip……" run successfully. why does this happen?
Are there other tools acting as the role of monero-etl who can read the monero blockchain into csv for me?

**Comment by emesik** [comment]
There's no executable named `monero-python`. This software is a module you may import but not run directly.

And there's nothing called `monero-etl`; it must be your code or some other module.

**Comment by yourprogrameiswrong** [comment]
Thanks for replying my question.
the project called monero etl has a link towards your module, so I misunderstand that it is part of your program. our team has tryed the code they provided&nbsp; in&nbsp;2018. however, it can't use today for out-of-date.



---Original---
From: "Michał ***@***.***&gt;
Date: Sun, Aug 15, 2021 04:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [monero-ecosystem/monero-python] from the monero-etl : after run "pip install git+https://github.com/emesik/monero-python.git" ,I can not find monero-python.py (#99)




 
Closed #99.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
